steps:
- name: gcr.io/k8s-skaffold/skaffold:v0.15.1
  args:
    - bash
    - -c
    - |
      gcloud container clusters get-credentials cluster --zone us-central1-a --project philde-testing-2
      skaffold run
