---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "nginx"
  namespace: "default"
  labels:
    app: "nginx"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - name: "gcb-test"
        image: "gcr.io/philde-testing-2/github.com/pdeslaur/gcb-test"
---
apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-hpa"
  namespace: "default"
  labels:
    app: "nginx"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
