apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcb-test-1
  name: gcb-test-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcb-test-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gcb-test-1
    spec:
      containers:
        - image: gcr.io/philde-testing-2/github.com/pdeslaur/gcb-test
          imagePullPolicy: IfNotPresent
          name: gcb-test-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: gcb-test-1
  name: gcb-test-1-hpa-nrfy
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gcb-test-1
