apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: automated-deployment
  name: automated-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automated-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: automated-deployment
    spec:
      containers:
        - image: gcr.io/philde-demo/github.com/pdeslaur/gcb-test
          imagePullPolicy: IfNotPresent
          name: gcb-test
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: automated-deployment
  name: automated-deployment-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: automated-deployment
