apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-6
  name: nginx-6
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-6
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx-6
    spec:
      containers:
        - image: 'gcr.io/philde-testing-2/github.com/pdeslaur/gcb-test:79a80a1'
          imagePullPolicy: IfNotPresent
          name: gcb-test
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: nginx-6
  name: nginx-6-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-6

